### ISSUE TITLE
GCM support

### ISSUE THREAD

**Issue by Dadoum** [ichordev/encrypt-d#1]
Hey! 
Thanks for your work, I was just wondering if you had any plan to add GCM support even if it's not in the tiny AES code in C.

As far as I understand, GCM makes use of CTR so some code should be reusable. 
My use case is in a server protocol that requires an AES256-GCM decryption, and currently I have to use openSSL just for that decryption.

**Comment by ichordev** [comment]
I wasn’t really planning on it, but if there’s a simple robust implementation of AES-GCM that I could reference then it’s not out of the question. Ideally something with some tests.

**Comment by Dadoum** [comment]
Thanks for the quick answer.
I found those two in C with tests ([aes-gcm](https://github.com/michaeljclark/aes-gcm/blob/master/src/aes-gcm.c) and [SharedAES-GCM](https://github.com/mko-x/SharedAES-GCM/blob/master/Sources/gcm.c)). If needed, I can also provide in Base64 the specific decryption parameters used in my project and the OpenSSL output.

**Comment by ichordev** [comment]
Thanks. I’ll have a look into those when I’ve got some free time and I’ll see what I can do. :)

**Comment by Dadoum** [comment]
(I switched to botan in the meantime, so it doesn't matter now, but thanks for your time)
